/**
 * Instrument Suggestion Types
 * AI-powered music instrument recommendation system
 */

export type ExperienceLevel = 'beginner' | 'intermediate' | 'advanced';

export type SuggestionPurpose = 'band' | 'solo' | 'studio' | 'production';

export type InstrumentCategory = 
  | 'strings' 
  | 'keyboards' 
  | 'percussion' 
  | 'wind' 
  | 'electronic' 
  | 'vocals' 
  | 'amplification' 
  | 'recording';

export interface InstrumentSuggestion {
  name: string;
  image: string;
  score: number;
  headline: string; // Catchy one-liner
  matchReason: string;
  learningCurve: 'easy' | 'moderate' | 'challenging';
  timeToBasics: string; // e.g., "2-4 weeks"
  proTip: string; // Actionable getting started tip
  famousPlayers: string[]; // Famous musicians for inspiration
  perfectFor: string; // Short tag like "rhythm section"
  genres: string[];
  difficulty: ExperienceLevel;
  category: InstrumentCategory;
  description: string;
  relatedInstruments: string[];
  aiPowered?: boolean; // Indicates if this suggestion was generated by AI
  aiProvider?: string; // Which AI model generated this
}

export interface InstrumentSuggestionRequest {
  action: 'suggest';
  genres?: string[];
  currentInstruments?: string[];
  experienceLevel?: ExperienceLevel;
  purpose?: SuggestionPurpose;
  limit?: number;
  useAI?: boolean; // Enable/disable AI-powered suggestions
}

export interface InstrumentSuggestionResponse {
  suggestions: InstrumentSuggestion[];
  message: string;
  aiPowered: boolean; // Indicates if suggestions were AI-generated
}

export interface GenresResponse {
  genres: string[];
  message: string;
}

export interface CategoriesResponse {
  categories: { [category: string]: string[] };
  message: string;
}

export interface InstrumentInfoRequest {
  action: 'get-instrument-info';
  instrumentName: string;
}

export interface InstrumentInfo {
  name: string;
  image: string;
  genres: string[];
  difficulty: ExperienceLevel;
  category: InstrumentCategory;
  description: string;
  relatedInstruments: string[];
}

export interface InstrumentInfoResponse {
  instrument: InstrumentInfo;
  message: string;
}

// Predefined genre list for UI selection
export const MUSIC_GENRES = [
  'Rock',
  'Metal',
  'Jazz',
  'Blues',
  'Pop',
  'Electronic',
  'EDM',
  'Hip-Hop',
  'R&B',
  'Folk',
  'Country',
  'Classical',
  'Acoustic',
  'Indie',
  'Funk',
  'Soul',
  'Reggae',
  'Latin',
  'World Music',
  'Punk',
  'Alternative',
  'Gospel',
  'Worship',
] as const;

export type MusicGenre = typeof MUSIC_GENRES[number];

// Purpose descriptions for UI
export const PURPOSE_OPTIONS = [
  { value: 'band' as SuggestionPurpose, label: 'Band/Group', icon: 'people', description: 'Playing with others in a band' },
  { value: 'solo' as SuggestionPurpose, label: 'Solo Performance', icon: 'person', description: 'Performing alone' },
  { value: 'studio' as SuggestionPurpose, label: 'Studio Recording', icon: 'mic', description: 'Recording music in a studio' },
  { value: 'production' as SuggestionPurpose, label: 'Music Production', icon: 'desktop', description: 'Creating electronic/produced music' },
] as const;

// Experience level descriptions for UI
export const EXPERIENCE_OPTIONS = [
  { value: 'beginner' as ExperienceLevel, label: 'Beginner', description: 'Just starting out' },
  { value: 'intermediate' as ExperienceLevel, label: 'Intermediate', description: 'Some experience playing' },
  { value: 'advanced' as ExperienceLevel, label: 'Advanced', description: 'Professional level' },
] as const;
