[functions.verification-redirect]
verify_jwt = false
[functions.didit-webhook]
verify_jwt = false
[functions.manage-profile]
verify_jwt = false
[functions.manage-bookings]
verify_jwt = false
[functions.manage-notifications]
verify_jwt = false
[functions.manage-listings]
verify_jwt = false
[functions.manage-details]
verify_jwt = false
[functions.verify-identity]
verify_jwt = false
[functions.home-feed]
verify_jwt = false
[functions.search-content]
verify_jwt = false