import type { TextStyle, ViewStyle } from "react-native";

import { radius, typography } from "./tokens";

type FormStyleMap = Record<string, TextStyle | ViewStyle>;

/**
 * Shared visual primitives for the app's task-focused add/edit screens.
 * These intentionally contain presentation only; form state and behavior stay
 * owned by each route.
 */
export const wizardFormStyles: FormStyleMap = {
  stepIndicatorContainer: {
    marginHorizontal: -20,
    marginTop: 0,
    marginBottom: 16,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  progressLineBg: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 3,
    top: 18,
    zIndex: 0,
  },
  activeProgressLine: {
    position: "absolute",
    left: 0,
    height: 3,
    top: 18,
    zIndex: 0,
  },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
  },
  stepText: {
    width: "100%",
    marginTop: 6,
    fontSize: 11,
    lineHeight: 15,
    textAlign: "center",
    includeFontPadding: false,
    fontFamily: typography.medium,
  },
  formContainer: {
    flex: 1,
    paddingHorizontal: 20,
    marginTop: 0,
  },
  sectionTitle: {
    marginBottom: 20,
    fontSize: 20,
    lineHeight: 26,
    textAlign: "left",
    letterSpacing: -0.35,
    fontFamily: typography.title,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontFamily: typography.bold,
  },
  inputWrapper: {
    minHeight: 52,
    borderRadius: radius.input,
    borderWidth: 1,
    overflow: "hidden",
  },
  textInput: {
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "left",
    textAlignVertical: "center",
    fontFamily: typography.body,
  },
  navigationButtons: {
    marginTop: 28,
    marginBottom: 16,
    gap: 12,
  },
  navigationButtonRow: {
    width: "100%",
    flexDirection: "row",
    gap: 12,
  },
  backBtn: {
    flex: 1,
    minHeight: 52,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: radius.button,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  backBtnText: {
    fontSize: 15,
    fontFamily: typography.semibold,
  },
  nextBtn: {
    flex: 1,
    minHeight: 52,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: radius.button,
    alignItems: "center",
    justifyContent: "center",
  },
  nextBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontFamily: typography.bold,
  },
};

export const editFormStyles: FormStyleMap = {
  scrollContent: {
    paddingTop: 8,
    paddingHorizontal: 20,
    paddingBottom: 160,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 28,
    marginBottom: 16,
  },
  firstSectionHeader: {
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 19,
    lineHeight: 25,
    letterSpacing: -0.3,
    fontFamily: typography.title,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontFamily: typography.bold,
  },
  inputWrapper: {
    minHeight: 52,
    borderRadius: radius.input,
    borderWidth: 1,
    overflow: "hidden",
  },
  input: {
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "left",
    textAlignVertical: "center",
    fontFamily: typography.body,
  },
  textInput: {
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "left",
    textAlignVertical: "center",
    fontFamily: typography.body,
  },
  footerActions: {
    marginTop: 28,
    marginBottom: 20,
    gap: 12,
  },
  saveButton: {
    minHeight: 52,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: radius.button,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontFamily: typography.bold,
  },
  cancelButton: {
    minHeight: 52,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: radius.button,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
};

export const productionFormStyles: FormStyleMap = {
  content: {
    paddingHorizontal: 20,
    paddingTop: 8,
    gap: 16,
  },
  heroCard: {
    padding: 16,
    borderWidth: 1,
    borderRadius: radius.card,
  },
  heroIcon: {
    width: 44,
    height: 44,
    marginBottom: 12,
    borderRadius: radius.control,
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitle: {
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: -0.35,
    fontFamily: typography.title,
  },
  heroText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 20,
    fontFamily: typography.body,
  },
  formCard: {
    padding: 16,
    borderWidth: 1,
    borderRadius: radius.card,
  },
  label: {
    marginTop: 16,
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontFamily: typography.bold,
  },
  input: {
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderWidth: 1,
    borderRadius: radius.input,
    fontSize: 14,
    lineHeight: 20,
    textAlignVertical: "center",
    fontFamily: typography.body,
  },
  descriptionHint: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: typography.body,
  },
  helperText: {
    marginTop: 12,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: typography.medium,
  },
  submitBtn: {
    minHeight: 52,
    marginTop: 24,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: radius.button,
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontFamily: typography.bold,
  },
};

export const profileFormStyles: FormStyleMap = {
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 150,
  },
  editProfileSkeletonContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 150,
  },
  field: {
    marginBottom: 20,
  },
  label: {
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontFamily: typography.bold,
  },
  input: {
    minHeight: 52,
    height: 52,
    paddingHorizontal: 14,
    paddingVertical: 0,
    borderWidth: 1,
    borderRadius: radius.input,
    fontSize: 14,
    lineHeight: 20,
    includeFontPadding: false,
    textAlignVertical: "center",
    fontFamily: typography.body,
  },
  textArea: {
    minHeight: 110,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderRadius: radius.input,
    fontSize: 14,
    lineHeight: 20,
    includeFontPadding: false,
    textAlign: "left",
    textAlignVertical: "top",
    fontFamily: typography.body,
  },
  saveBtn: {
    minHeight: 52,
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: radius.button,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontFamily: typography.bold,
  },
  cancelBtn: {
    minHeight: 52,
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: radius.button,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelBtnText: {
    fontSize: 15,
    fontFamily: typography.semibold,
  },
};
