import { StyleSheet } from "react-native";

export const colors = {
  background: "#07110d",
  surface: "#0d1b15",
  surfaceRaised: "#12241b",
  border: "#244033",
  text: "#eef9f1",
  muted: "#91aa9a",
  accent: "#45d17a",
  accentDark: "#153c25",
  danger: "#ff6b6b",
  warning: "#f4c95d",
  info: "#72a7ff",
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  content: { width: "100%", maxWidth: 1280, alignSelf: "center", padding: 24, gap: 18 },
  hero: { paddingVertical: 12, gap: 6 },
  eyebrow: { color: colors.accent, fontSize: 12, letterSpacing: 1.8, fontFamily: "Poppins_600SemiBold" },
  title: { color: colors.text, fontSize: 30, fontFamily: "Poppins_700Bold" },
  subtitle: { color: colors.muted, maxWidth: 780, lineHeight: 22, fontFamily: "Poppins_400Regular" },
  banner: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 14, padding: 14, gap: 4 },
  bannerTitle: { color: colors.text, fontFamily: "Poppins_600SemiBold" },
  bannerText: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  tabs: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tab: { borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 16, paddingVertical: 9 },
  tabActive: { borderColor: colors.accent, backgroundColor: colors.accentDark },
  tabText: { color: colors.muted, fontFamily: "Poppins_500Medium" },
  tabTextActive: { color: colors.accent },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 14 },
  field: { flexGrow: 1, flexBasis: 260, gap: 6 },
  fieldWide: { flexBasis: 540 },
  label: { color: colors.text, fontSize: 13, fontFamily: "Poppins_500Medium" },
  hint: { color: colors.muted, fontSize: 11, lineHeight: 16 },
  input: { color: colors.text, backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 11, minHeight: 44 },
  inputMultiline: { minHeight: 92, textAlignVertical: "top" },
  card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 16, padding: 18, gap: 14 },
  cardTitle: { color: colors.text, fontSize: 18, fontFamily: "Poppins_600SemiBold" },
  sectionTitle: { color: colors.text, fontSize: 14, fontFamily: "Poppins_600SemiBold", marginTop: 2 },
  buttonRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  button: { backgroundColor: colors.accent, borderRadius: 10, paddingHorizontal: 18, paddingVertical: 12, alignItems: "center", justifyContent: "center" },
  buttonSecondary: { backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderWidth: 1 },
  buttonDestructive: { backgroundColor: "transparent", borderColor: colors.danger, borderWidth: 1 },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: "#04150a", fontFamily: "Poppins_600SemiBold" },
  buttonTextSecondary: { color: colors.text },
  buttonTextDestructive: { color: colors.danger },
  checkRow: { flexDirection: "row", alignItems: "center", gap: 9 },
  checkbox: { width: 20, height: 20, borderRadius: 5, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
  checkboxChecked: { borderColor: colors.accent, backgroundColor: colors.accent },
  checkboxTick: { color: "#04150a", fontFamily: "Poppins_700Bold" },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  counterCard: { backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 14, gap: 14 },
  counterHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  counterControls: { flexDirection: "row", alignItems: "center", gap: 10 },
  counterButton: { width: 40, height: 40, borderRadius: 10, borderColor: colors.border, borderWidth: 1, backgroundColor: colors.accentDark, alignItems: "center", justifyContent: "center" },
  counterButtonText: { color: colors.accent, fontSize: 22, lineHeight: 25, fontFamily: "Poppins_600SemiBold" },
  counterValue: { minWidth: 28, color: colors.text, textAlign: "center", fontSize: 20, fontFamily: "Poppins_600SemiBold" },
  groupTypeList: { gap: 8 },
  groupTypeRow: { flexDirection: "row", alignItems: "center", gap: 10, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 8 },
  customGroupTypeRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  gigPreview: { flexDirection: "row", alignItems: "center", gap: 12, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 12, backgroundColor: colors.surfaceRaised },
  gigPreviewImage: { width: 52, height: 52, borderRadius: 26 },
  gigPreviewPlaceholder: { width: 52, height: 52, borderRadius: 26, alignItems: "center", justifyContent: "center", backgroundColor: colors.accentDark },
  gigPreviewPlaceholderText: { color: colors.accent, fontSize: 24, fontFamily: "Poppins_600SemiBold" },
  pill: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: 999, backgroundColor: colors.surfaceRaised },
  pillText: { color: colors.muted, fontSize: 11 },
  stage: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 11, gap: 5 },
  stageHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  stageLabel: { color: colors.text, flex: 1, fontFamily: "Poppins_500Medium" },
  stageMessage: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  mono: { color: "#b8d6c2", backgroundColor: "#07110d", borderRadius: 9, padding: 12, fontFamily: "monospace", fontSize: 12, lineHeight: 18 },
  error: { color: colors.danger, lineHeight: 20 },
  warning: { color: colors.warning, lineHeight: 20 },
  success: { color: colors.accent, lineHeight: 20 },
  divider: { height: 1, backgroundColor: colors.border },
  empty: { color: colors.muted, textAlign: "center", paddingVertical: 24 },
});
